node { 
    withCredentials([[$class: 'UsernamePasswordMultiBinding', 
        credentialsId: 'docker-login', 
        usernameVariable: 'DOCKER_USER_ID', 
        passwordVariable: 'DOCKER_USER_PASSWORD']]) 
    
    { 
     stage('Pull') {
           git branch: 'develop', credentialsId: 'github-access-token', url: 'https://github.com/kimyoonseong/FindFounder.git'
        }
        

      stage('Build') {
            sh(script: '''yes | sudo docker image prune -a''') 
            sh(script: '''sudo docker build -f /var/lib/jenkins/workspace/jenkins-FindFounder/Flask/Dockerfile -t myflask .''')
        }

      stage('Tag') {
              sh(script: '''sudo docker tag myflask ${DOCKER_USER_ID}/myflask:${BUILD_NUMBER}''') 
            }

      stage('Push') {
            sh(script: 'sudo docker login -u ${DOCKER_USER_ID} -p ${DOCKER_USER_PASSWORD}') 
            sh(script: 'sudo docker push ${DOCKER_USER_ID}/myflask:${BUILD_NUMBER}') 
        }
      
      stage('Deploy') {
            sshagent(credentials: ['aws-ssh-pem-key']) {
                sh(script: 'ssh -o StrictHostKeyChecking=no ubuntu@15.165.229.232 "sudo docker rm -f myflask"')
                sh(script: 'ssh ubuntu@15.165.229.232 "sudo docker run --name myflask TZ=Asia/Seoul -p 5000:5000 -d -t \${DOCKER_USER_ID}/myflask:\${BUILD_NUMBER}"')
        }
    }

    stage('Cleaning up') { 
              sh "sudo docker rmi ${DOCKER_USER_ID}/myflask:${BUILD_NUMBER}" // sudo docker image 제거
      } 
    }
  }
